### PR TITLE
enable Sourcelink

### PR DESCRIPTION
**Pull request by MagicAndre1981**
with this change we can step into the code if you include the PDB into the nuget package.

### CODE REVIEW

**Comment by MagicAndre1981** [comment]
@pierresprim have you looked at it?

**Comment by MagicAndre1981** [comment]
@pierresprim thanks for merging. When Can we get the updated nugets? I want to replace the older version I used before with your one as yours is the most recent version which gets new fixes.

**Comment by pierresprim** [comment]
I uploaded the new packages on NuGet, you can download them now. Thanks for using them!

**Comment by MagicAndre1981** [comment]
> I uploaded the new packages on NuGet, you can download them now. 

and it is time for a new update. Microsoft released .net core 3.0 and so some dependencies needs to be updated to RTM bits and System.Threading.Tasks.Extensions should stay at last stable 4.5.3 because it is newer.

Also which VS do you use? Nuget is broken for me in 2017 when I use your project and I have to reinstall all nugets in new **PackageReference Include** format.

**Comment by MagicAndre1981** [comment]
@pierresprim 

I see you still work on it in develop branch. Can you modify the code to use PackageReference Include and not the ugly old way you did which causes compile/consume issues.

**Comment by MagicAndre1981** [comment]
@pierresprim

I tried the [2.0.0-preview1](https://www.nuget.org/packages/WinCopies.WindowsAPICodePack/2.0.0-preview1) and it is working fine. I can step into code.

What in detail is now new/fixed since? Checking [each item for what is changed](https://github.com/aybe/Windows-API-Code-Pack-1.1/compare/develop...pierresprim:develop) is slow

**Comment by pierresprim** [comment]
As written at [https://github.com/pierresprim/Windows-API-Code-Pack/blob/master/CHANGELOG.md](https://github.com/pierresprim/Windows-API-Code-Pack/blob/master/CHANGELOG.md), the main changes are:

- some types have moved;
- a native implementation for the Windows Portable Devices API is available;
- the Single Instance App feature was disabbled for .Net Core.

The 2.0.0-preview2 will also be available soon.

**Pull request merged**
